(* Insert header here *)
(* 1a *)
(*(\c.c(\a.\b.b))((\a.\b.\f.f a b)p q)*)
(*⇒B(λa.λb.λf.f a b) p q (λa.λb.b)*)
(*⇒B(λb.λf.f p b) q (λa.λb.b)*)
(*⇒B(λf.f p q) (λa.λb.b)*)
(*⇒B(λa.λb.b) p q*)
(*⇒B(λb.b) q
(*⇒B q*)
(* 1b *)
(*(\c.c(\a.\b.b))((\a.\b.\f.f a b)p q)*)
(*((\a.\b.\f.f a b)p q(\c.c(\a.\b.b))*)
(*⇒B((\b.\f.f p b)q(\c.c(\a.\b.b))*)
(*⇒B((.\f.f p q)(\c.c(\a.\b.b))*)
(*⇒B (\a.\b.b)p q*)
(*⇒B (\b.b)q*)
(*⇒B q)
(* 2a *)
(* (\x.\y.(mul x((\x.(add x 3))y)))7 8 *)
(*⇒ a(\x.\y.(mul x(\x'.(add x' 3)y)))7 8 *)
(*⇒ B(\y.(mul 7(\x'.(add x' 3)y)))8 *)
(*⇒ B((mul 7(\x'.(add x' 3))8))*)
(*⇒ δ(7*(\x'.(add x' 3))8)*)
(*⇒ B(7*(add 8 3))*)
(*⇒ δ(7*11)*)
(*⇒ 77*)
(* 2b *)
(* (\x.\y.(mul x((\x.(add x 3))y)))7 8 *)
(*⇒δ(\x.\y.(mul x((\x.(x+3))y)))7 8 *)
(*⇒a(\x'.\y.(mul x'((\x.(x+3))y)))7 8 *)
(*⇒B(\x'.\y.(mul x'((7+3))y)) 8 *)
(*⇒(\x'.\y.(mul x'(10)y)) 8 *)
(*⇒δ(\x'.\y.(x'* 10)y) 8 *)
(*⇒B(\y.(8* 10)y)*)
(*⇒B(\y.(80)y)*)
(*⇒B 80)
(* 2c *)
fun f(X:int,Y:int)=>X*Y; 
(* λx.λy.mul x (add y 3)*)
(* Example query: f 7 8 *)

